// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvec6X-dNl0d2IZ7M5o3HAnD_hCBRLkDg',
    appId: '1:782850045185:web:1c02d6f39a3203b78b1700',
    messagingSenderId: '782850045185',
    projectId: 'periodtracker-e847a',
    authDomain: 'periodtracker-e847a.firebaseapp.com',
    storageBucket: 'periodtracker-e847a.appspot.com',
    measurementId: 'G-M247GNPRT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyKq5IK4Mr3lauIep6e7s3SzMWy6pzdE',
    appId: '1:782850045185:android:3f99fae483151f518b1700',
    messagingSenderId: '782850045185',
    projectId: 'periodtracker-e847a',
    storageBucket: 'periodtracker-e847a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy-__DXZYasXeiIf6MY5B-SXjp910IQe0',
    appId: '1:782850045185:ios:2a10aa7238d18b9e8b1700',
    messagingSenderId: '782850045185',
    projectId: 'periodtracker-e847a',
    storageBucket: 'periodtracker-e847a.appspot.com',
    iosBundleId: 'com.example.periodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy-__DXZYasXeiIf6MY5B-SXjp910IQe0',
    appId: '1:782850045185:ios:299174bd2de8f08a8b1700',
    messagingSenderId: '782850045185',
    projectId: 'periodtracker-e847a',
    storageBucket: 'periodtracker-e847a.appspot.com',
    iosBundleId: 'com.example.periodApp.RunnerTests',
  );
}
